apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: react-express-mongodb
data:
  MONGODB_DATABASE: "mern_app"
  NODE_ENV: "production"
  PORT: "5000"
  REACT_APP_API_URL: "http://backend-service:5000"