apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: react-express-mongodb
type: Opaque
data:
  MONGODB_USERNAME: YWRtaW4=
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM=
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9tZXJuX2FwcA==